package com.task.newapp.api

const val login_url = "/api_v1/login"
const val reset_password_url = "api_v1/forgot-password-reset-submit"
const val send_code_forgot_url = "/api_v1/forgot-password-code"
const val verify_OTP_url = "/api_v1/forgot-password-verify-code"
const val register_url = "/api_v1/register"
const val check_username_url = "/api_v1/update-accointid/{user}"
const val get_username_url = "/api_v1/generate-accointid/{user}"
const val send_code_normal_url = "/api_v1/user-mail-verification"
const val verify_OTP_normal_url = "/api_v1/user-check-verification"
const val get_unread_messages = "/api_v1/get_unread_message"
const val hook_chat = "api_v1/hook-chat"
const val archive_chat = "api_v1/archive-chat"
const val delete_chat = "api_v1/delete_chat-chat"
const val get_all_posts = "/api_v1/get-all-posts/{limit}/{offset}"
const val add_postlikeunlike = "/api_v1/post_like"
const val post_comment = "/api_v1/post_comment"
const val postSaveUnsave = "/api_v1/post-save"
const val allpostcomment = "/api_v1/post-comment-detail"
const val get_myprofile_url = "/api_v1/view_profile/{user}"
const val set_usersetting_url = "/api_v1/user-settings"
const val get_user_follower_following_url = "/api_v1/user-follower-following"
const val get_user_profileviewer = "/api_v1/profile_view_list"
const val set_user_follow_unfollow = "/api_v1/follow"
const val set_profile_group_page_friend_post = "/api_v1/profile_group_page_friend_post"
const val set_friendsetting_url = "/api_v1/friends-setting"
const val set_block_unblock_report_url = "/api_v1/block-report"
const val get_notification_tone = "/api_v1/get-notification-tone"
const val add_post = "/api_v1/post"


