package com.task.newapp.api

const val login_url = "/api_v1/login"
const val reset_password_url = "api_v1/forgot-password-reset-submit"
const val send_code_forgot_url = "/api_v1/forgot-password-code"
const val verify_OTP_url = "/api_v1/forgot-password-verify-code"
const val register_url = "/api_v1/register"
const val check_username_url = "/api_v1/update-accointid/{user}"
const val get_username_url = "/api_v1/generate-accointid/{user}"
const val send_code_normal_url = "/api_v1/user-mail-verification"
const val verify_OTP_normal_url = "/api_v1/user-check-verification"
const val get_unread_messages = "/api_v1/get_unread_message"
const val hook_chat = "api_v1/hook-chat"
const val archive_chat = "api_v1/archive-chat"
const val delete_chat = "api_v1/delete_chat-chat"
const val get_all_posts = "/api_v1/get-all-posts/{limit}/{offset}"
const val add_postlikeunlike = "/api_v1/post_like"
const val post_comment = "/api_v1/post_comment"
const val postSaveUnsave = "/api_v1/post-save"
const val allpostcomment = "/api_v1/post-comment-detail"